### ISSUE TITLE
How did you preprocess and load the Oscar dataset to the training script 


### ISSUE THREAD

**Issue by StephennFernandes** [puraminy/parsT5#1]
Hi there, could you please show me how did you clean the Oscar corpus and preprocess it to be able to train it on the training script

**Comment by puraminy** [comment]
Hi, 
The tokenization and training script in this repository is based on the huggingface flax example:


https://github.com/huggingface/transformers/tree/master/examples/flax/language-modeling

For preprocessing ant tokenization run the `t5_tokenizer_model.py`. You can refer to the above page for more information.
